#!/usr/bin/python3

from kubernetes import client, config
from decimal import Decimal
from prettytable import PrettyTable

config.load_kube_config()

t = PrettyTable(['Namespace', 'Requested CPU', 'Requested Memory'])

v1 = client.CoreV1Api()
namespaces = v1.list_namespace()
for namespace in namespaces.items:
    pod_list = v1.list_namespaced_pod(namespace.metadata.name)
    mem=0
    cpu=0
    for pod in pod_list.items:
        for container in pod.spec.containers:
            memstr = container.resources.requests["memory"]
            cpustr = container.resources.requests["cpu"] 
            if "Mi" in memstr or "mi" in memstr:
                mem+=int(memstr[:-2])
            if "Gi" in memstr or "gi" in memstr:
                mem+=1024*int(memstr[:-2])            
            if "m" in cpustr or "M" in cpustr:
                cpu+= Decimal(cpustr[:-1])
            else:
                cpu+= 1000 * Decimal(cpustr[:-1])
    t.add_row([namespace.metadata.name, cpu, mem]) 
       
print (t)